### ISSUE TITLE
Not working in Qlik Sense Server.

### ISSUE THREAD

**Issue by Rut16** [ClimberAB/ClimberContainer#1]
This extension is working properly on Qlik Sense Desktop but doesn't work on Qlik Sense Server.

**Comment by Rut16** [comment]
Qlik Sense 3.2 SR4 
qliksenseserver:10.28.2
my desktop version is feb 2018.
Issue:  I am able to see the extension in my extension list. but when I add objects from master items it isn't rendered in the container.Please find the below screenshot
![image](https://user-images.githubusercontent.com/26433389/36830535-07931e8c-1d4a-11e8-9fae-25591b2b3919.png)
.

**Comment by kfsjostrand** [comment]
This version doesn't support QS 3.2 and we don't test our extensions in versions prior to November 2017 for our free tier. If you want to learn more about our supported offerings navigate to https://www.climber.se/pl-extension-for-qlik-sense
