### ISSUE TITLE
Extension doesn't load with June 2018 Qlik Sense release

### ISSUE THREAD

**Issue by jparis** [ClimberAB/ClimberContainer#10]
Extension fails to load in June 2018 release. Works fine in February 2018.

Error in console:

> Error in extension 'extensions/cl-container/cl-container': Can not use internal module 'extensions/cl-container/cl-container'.
```(anonymous) @ /resources/chunks/57.0c7551bab659999f26cd.js:576```

**Comment by MichaelClimber** [comment]
Thanks for letting us know. We expect many of the extensions to fail with the new June release. Qlik has flagged a lot of changes coming in Qlik over the next few releases. Our subscribing customers will get updates from us and we will of course also update GitHub with versions supporting June too.

**Comment by kfsjostrand** [comment]
Fixed in latest release. Check the changelog and readme.
https://github.com/ClimberAB/ClimberContainer/releases/tag/v1.1.0
