### ISSUE TITLE
June 2018 Qlik Sense Server

### ISSUE THREAD

**Issue by asimlilani** [ClimberAB/ClimberContainer#11]
I just upgraded to Qlik Sense Server June 2018 and this extension just stopped working. I redownloaded from Github and reuploaded however it didnt resolve it. 

The [error](url
<img width="907" alt="screenshot at jun 28 14-24-35" src="https://user-images.githubusercontent.com/19389890/42053462-9783d052-7adf-11e8-8f57-35a03f46ec24.png">
) message is:

Invalid Visualization
The visualization was not found on the server: cl-container

**Comment by FaridChaud** [comment]
I've a same problem!

**Comment by Lojdquist** [comment]
Try downloading the zip again, should be working now.

**Comment by FaridChaud** [comment]
not yet, same problem

**Comment by Lojdquist** [comment]
Hi, could you try to clear the cache and try again?

https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

The original link should be working, but try redownloading the extension from this link just in case:
https://github.com/ClimberAB/ClimberContainer/releases/download/v1.1.0/cl-container-v1.1.0.zip

**Comment by asimlilani** [comment]
I just installed it again and it works for me on Qlik Sense June 2018. Thank you!
