### ISSUE TITLE
multiple object reloads based on selections

### ISSUE THREAD

**Issue by zucoa** [ClimberAB/ClimberContainer#12]
Hello - I'm updating an application and set of ShowHide extensions to climber container v1.1.0 throughout this mashup: [https://edap.epa.gov/public/extensions/nei_report_2014/dashboard.html#sector-db](url)

In my working copy, as I make selections in the filter panes I'm getting multiple loading icons and a bit of a slow response from the container (see pic). Are all of the objects updating in the container simultaneously or just the active container object? Is this the expected behavior or are there ways to optimize...possibly only update the active container object? Many thanks, great stuff!

![climber-container-v1 1 0-doubleload](https://user-images.githubusercontent.com/22177573/43013891-58273a26-8c18-11e8-9aa8-cade5ab3534c.PNG)

**Comment by kfsjostrand** [comment]
Hi zucoa,
Nice to see our extensions being used on a public web page. Thanks for sharing.
On load the Climber Container only request the active visualization. The default behavior when changing tabs the visualizations are not to close the visualization and cache it for quicker switching between tabs. This cache can be disabled in the property panel under Apperance/General/Use visualization cache. But I don't think that's what causing your issue.
I used Chrome when I visited your mashup and didn't experience any of the issues you are describing. Did you manage to sort it out? What browsers are having this issues?
Regards
Karl

**Comment by zucoa** [comment]
@kfsjostrand 
Hi Karl - I just updated the right side objects to climber container. It may take a little while through making selections and then deselections from the filter panes, but eventually that double loading icon appears. It is intermittent so there's no hard and fast steps to recreate.

**Comment by edwardhallgren** [comment]
Hi, visit your website and the performance seems okay for me. Br Edward
