### ISSUE TITLE
Can' take snapshot 

### ISSUE THREAD

**Issue by Nisharai22** [ClimberAB/ClimberContainer#13]
Hi, 
Can you please add that feature as well, if user want to take the snapshot and add it in story then it's not possible.

**Comment by edwardhallgren** [comment]
Hi,

This should be implemented.

Check if this option i enabled.

Br
Edward

![image](https://user-images.githubusercontent.com/27728137/43763038-eca9ffd4-9a29-11e8-8892-73979cc69483.png)

**Comment by Nisharai22** [comment]
Thanks.


Regards,
Nisha Choudhry
