### ISSUE TITLE
Export in a container Internet Explorer

### ISSUE THREAD

**Issue by PeterVanOers** [ClimberAB/ClimberContainer#15]
Hi,
When using Internet Explorer to export a pivot in a container is ends up with an error.

![image](https://user-images.githubusercontent.com/37449405/45624691-54291880-ba8b-11e8-855c-0df643f59713.png)
 It's dutch so I'll try to translate the message:

The property of the method includes is not supported by this object.

QS is the 2018 June version but the error is the samen on a 2018 September version. 

It works using Chrome as a browser.

Tnx
Peter van Oers.

**Comment by edwardhallgren** [comment]
Hi, this is fixed in the latest version. Br Edward
