### ISSUE TITLE
No pointer when used as a Single Object

### ISSUE THREAD

**Issue by countnazgul** [ClimberAB/ClimberContainer#17]
### Versions
* Extension version: 1.1.2
* Qlik Sense: November 2017 (Desktop and Enterprise)
* Browser:  Chrome

### Description
When the extension is used as a single object (using the single configuration) the cursor over the tabs is no longer pointer

In QS Desktop (same for QS Enterprise)
![screenshot1](https://user-images.githubusercontent.com/22850/49009095-7c0dba00-f167-11e8-9c26-3f4332636136.png)

As single object  (same for QS Enterprise)
![screenshot2](https://user-images.githubusercontent.com/22850/49009104-8334c800-f167-11e8-946c-6625167ef48e.png)

### Console errors
n/a

### Steps to Reproduce

1. Open QS dev hub
2. Choose Single Configurator
3. Select an app
4. Navigate to the sheet where the container object is located
5. Select the container object or select the sheet where the container is
6. Press the View button (top right)
7. The cursor is no longer pointer in the browser

##### Expected behavior

The cursor should be pointer over the tab when the extension is used as a single object or part of a single object sheet

**Comment by edwardhallgren** [comment]
Hi, this should be fixed in the latest version. Br Edward

**Comment by countnazgul** [comment]
Yep it is :) Thanks!
