### ISSUE TITLE
Disable export

### ISSUE THREAD

**Issue by countnazgul** [ClimberAB/ClimberContainer#18]
### Versions
* Extension version: 1.2.0
* Qlik Sense: June 2018
* Browser:  Chrome

*Extension version can be found under About in the property panel of the extension in Edit-mode or in the Qlik Sense Dev-hub.*  

### Description
We have implemented security rules which are preventing the data export for a specific apps but if the QS object(s) are part of the extension container i can still see `Export data` option in the context menu. Is it possible to switch off the export capability on right click somehow?

### Console errors
[Check the console of the browser for errors]  

*Chrome: Ctrl + Shift + J*   
*Internet Explorer: F12, reload the page after, since IE doesn't keep history*  
*Firefox: Ctrl + Shift + K*

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.

(There are settings in the extension for disabling the export in the context menu. Check under Appearance\Context Menu)
