### ISSUE TITLE
confirm selection and maximize icon overlapping

### ISSUE THREAD

**Issue by zucoa** [ClimberAB/ClimberContainer#19]
### Versions
* Extension version: 1.3.0
* Qlik Sense: Feb 2019
* Browser:  Chrome

*Extension version can be found under About in the property panel of the extension in Edit-mode or in the Qlik Sense Dev-hub.*  

### Description
Hello - I'd like to be able to keep the maximize option enabled and confirm selections in chart objects; however, the maximize icon is overlaying the confirm button in many objects so I have to disable it most of the time. Can we have both or modify the z-index in some way?

![image](https://user-images.githubusercontent.com/22177573/55967744-d7d56d00-5c48-11e9-819e-af1ec7c620b5.png)

### Console errors
none

### Steps to Reproduce

1. Enable maximize 
2. Embed bar chart into container
3. Make selection in bar chart
4. Attempt to confirm selection

##### Expected behavior
When making a selection, have the selection bar pane take precedence over maximize. When not making selections, have maximize icon take precedence.

**Comment by zucoa** [comment]
I added a html object and used this which seems to be a workaround:
.qv-object-nav { top: 45px; }

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
