### ISSUE TITLE
Qlik Sense Feb 18

### ISSUE THREAD

**Issue by m1tch2000** [ClimberAB/ClimberContainer#2]
Hi,

I have downloaded the zip file and installed it in the extensions folder.  The extension appears in the Qlik Sense extension menu, however when I drag and drop the extension to the canvas I get an error "Invalid visualization.  The visualization was not found on the server: cl-container" Then it has a delete button.  I am running it on Qlik Sense desktop.  I have also named the folder cl-container.

Do you know what is causing this error?

Thanks
Gary

**Comment by m1tch2000** [comment]
Hi

I have created a new app from scratch and I get the same issue.

Thanks

Sent from my iPhone

On 7 Mar 2018, at 09:15, Edward Hallgren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Gary,

If you are creating a new app, is it still the same problem?

Br
Edward

**Comment by edwardhallgren** [comment]
Hi again Gary,

It seems like the adding of the extension to the folder might be wrong.

This is how it should look. Be sure that you don't have multiple folders to the extension.

![image](https://user-images.githubusercontent.com/27728137/37140017-7f5d9fbc-22b0-11e8-9857-3684ae71f6b7.png)

**Comment by m1tch2000** [comment]
Hi

I have noticed what the difference is based on your picture. The zip file that I downloaded does not have the cl-container.js file in it.

I downloaded the zip from the git hub site. Can the zip file be updated? Or has my work network stripped it out when downloading?

Thanks for your support
Gary

Sent from my iPhone

On 8 Mar 2018, at 08:12, Edward Hallgren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi again Gary,

It seems like the adding of the extension to the folder might be wrong.

This is how it should look. Be sure that you don't have multiple folders to the extension.

[image]<https://user-images.githubusercontent.com/27728137/37140017-7f5d9fbc-22b0-11e8-9857-3684ae71f6b7.png>

**Comment by m1tch2000** [comment]
Hi,

I have found what has caused my issue.  I have downloaded the extension from the button that says something like download version 1.0.1.  This version works.

The version I had the issue was from downloading it from the "clone or download" option and selecting the zip file.  This file does not contain the .js file.

My issue is now resolved.

Thanks

**Comment by edwardhallgren** [comment]
Hi, Great that you find the download button. 

We find a bug in our building process for "clone or download". We have fixed this now but we recommend to always download the latest version from the button.

Br
Edward
