### ISSUE TITLE
Export not working When using virtual proxy

### ISSUE THREAD

**Issue by sergioloza** [ClimberAB/ClimberContainer#21]
Using  1.3 
### Versions
* Extension version:
* Qlik Sense:  February 2018
* Browser:  Chrome

### Description
Hi team, facing an issue while trying to  export when using Virtual proxy.  I can export if I login directly but  the export is broken when using virtual proxy as the URL no longer contains the proxy value.  

### Steps to Reproduce

1. Setup virtual proxy for Qlik Sense 
2. Create a visualization that can be used in a container.  ( table and Pivot were tried)
3.  try to export data.  A page not found  should come about

##### Expected behavior
Exports to work when using proxy.

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.

(Take a look in Settings\Settings of the extension to find where to modify the export URL in mashups.)
