### ISSUE TITLE
not all icons load

### ISSUE THREAD

**Issue by zucoa** [ClimberAB/ClimberContainer#3]
So glad I found this extension! Qlik Icons seem to be the only icon set being found by the extension. All others are null.
![capture](https://user-images.githubusercontent.com/22177573/37569188-0f3d8bb8-2ab5-11e8-8f77-bda25640422b.PNG)

**Comment by edwardhallgren** [comment]
Hi,

What browser are you using and what verison of sense are you using?

Br
Edward

**Comment by zucoa** [comment]
@edwardhallgren 
Hello,
I tested in both QS Nov. 2017 and Feb. 2018 while in Chrome. Both have those null icon packs.

**Comment by edwardhallgren** [comment]
something went wrong in the building process. Check the file now. //Edward

**Comment by edwardhallgren** [comment]
Can you press f12 (developer tools) and take a print screen on the console? //Edward

**Comment by zucoa** [comment]
@edwardhallgren 
Sure thing. No console errors.
![capture](https://user-images.githubusercontent.com/22177573/37597302-6cf725e8-2b55-11e8-9db4-4503b1dca57d.PNG)

**Comment by edwardhallgren** [comment]
Hi, Please try the latest version v1.0.3.

Br
Edward

**Comment by zucoa** [comment]
@edwardhallgren 
Sorry, no change. I deleted old extensions and brought 1.0.3 into QS desktop February 2018 version.

**Comment by zwootten** [comment]
clear cache and reload page if viewing on web

**Comment by zucoa** [comment]
I'm testing in QS Desktop. I created a new sheet, cntrl + F5, brought in the new extension with no change. I closed my browser just in case. I closed QS desktop and reopened and repeated the steps with no change.

**Comment by edwardhallgren** [comment]
Try the latest version 1.0.4 //Edward

**Comment by edwardhallgren** [comment]
Please reopen the issue if problem still occurs //Edward

**Comment by zucoa** [comment]
@edwardhallgren 
Yup, working great thanks!
