### ISSUE TITLE
using table as tab content with dark background color

### ISSUE THREAD

**Issue by shofmannka** [ClimberAB/ClimberContainer#5]
Hello,
i have a table which has a calculated dark (red) background color. In this case the foreground color is white. If i use this tabel in your container the foreground color now has a grey color. What is the reason for that?
With regards,
Stefan Hofmann

**Comment by MichaelClimber** [comment]
We have not yet implemented support for custom themes so you can expect issues when deviating from the standard themes. Future updates may include better support for custom themes but since you build your own extension for custom themes there are many ways that can go wrong ;-).

**Comment by MichaelClimber** [comment]
Hmm... my colleagues pointed out that I may have misinterpreted your question. In case you are not talking about a custom theme for the entire table but just a normal cell background then that is of course something that should work. In that case please let us know your QS and browser versions so we can test our our end.

**Comment by shofmannka** [comment]
Hello Michael,
i am using Qlik Sense Desktop Version Feb. 2018 and Chrome Version 65.0.x
and yes I am talking not about a custom theme.
Thanks for your reply
With regards
Stefan Hofmann


Von: MichaelClimber [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. März 2018 12:40
An: ClimberAB/ClimberContainer <ClimberContainer@noreply.github.com>
Cc: Hofmann, Stefan <Stefan.Hofmann@kratzer-automation.com>; Author <author@noreply.github.com>
Betreff: Re: [ClimberAB/ClimberContainer] using table as tab content with dark background color (#5)


Hmm... my colleagues pointed out that I may have misinterpreted your question. In case you are not talking about a custom theme for the entire table but just a normal cell background then that is of course something that should work. In that case please let us know your QS and browser versions so we can test our our end.

**Comment by edwardhallgren** [comment]
Hi Stefan, It should be fixed in the latest version (v1.0.3) Please try it out //Edward

**Comment by shofmannka** [comment]
yes now it works fine. Thank you for fixing this bug. 
//Stefan
