### ISSUE TITLE
My bar chart and pie chart not appear after i move to another sheet.

### ISSUE THREAD

**Issue by azrul07** [ClimberAB/ClimberContainer#6]
Please help. Thanks.

![issue2](https://user-images.githubusercontent.com/38028149/38231568-b2182090-3745-11e8-93a7-c6b84c9ee48a.PNG)
![issue](https://user-images.githubusercontent.com/38028149/38231580-b9563ca2-3745-11e8-949d-86370c240948.PNG)

**Comment by MichaelClimber** [comment]
Hi,
Please supply details on versions of browser and Qlik Sense as well as any error messages in the browser console. 

Kind regards

Michael

**Comment by azrul07** [comment]
![capture](https://user-images.githubusercontent.com/38028149/38231877-2ef96d0c-3747-11e8-92a4-039e98997b3c.PNG)

Hi Michael.  As attached, not sure why it does not appear when i move to another sheet. first time move and move back, bar chart missing, Second time, pie chart missing. i also experience that I cannot even click the tab itself. Thanks.

**Comment by edwardhallgren** [comment]
Hi, we can't replicate the problem. Could you press f12 (developer tools chrome) in your web broswer and take a printscreen on the console log. 

Br 
Edward

**Comment by edwardhallgren** [comment]
Closed. Could not replicate the problem. Please attach the console log if you still having problems.
