### ISSUE TITLE
Export from Single API web page

### ISSUE THREAD

**Issue by YaroslavKharchenko** [ClimberAB/ClimberContainer#8]
Hi!
When I try to Export data from Table which is inside ClimberContainer nothing happens. I do this on web page opened using Single API.  In Chrome Console I see error message: single.js?1515426796317:1 Error: [$injector:unpr] Unknown provider: $exportDialogProvider <- $exportDialog
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=%24exportDialogProvider%20%3C-%20%24exportDialog
    at require.js:1
    at require.js:1
    at Object.i [as get] (require.js:1)
    at require.js:1
    at Object.i [as get] (require.js:1)
    at Object.m.getService (require.js:1)
    at t.select (cl-container.js:1)
    at p.i.selectItem (require.js:1)
    at fn (eval at compile (require.js:1), <anonymous>:4:471)
    at require.js:1
Qlik Sense February 2018, ClimberContainer 1.0.4.	
Please advise me how to fix this issue.

**Comment by edwardhallgren** [comment]
Hi, What version of sense do you have? //Edward

**Comment by YaroslavKharchenko** [comment]
> Qlik Sense February 2018, ClimberContainer 1.0.4.

**Comment by edwardhallgren** [comment]
Please try the latest version (1.0.5). Br Edward

**Comment by YaroslavKharchenko** [comment]
I tested ClimberContainer 1.0.5 on Qlik Sense April 2018. Even after I created new object the situation wasn't changed, I still receive the same error message in Chrome console.

**Comment by edwardhallgren** [comment]
Could you try to clear the cache in your web browser? (https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en )

**Comment by YaroslavKharchenko** [comment]
It didn't help.
![image](https://user-images.githubusercontent.com/13518588/40184324-9aedf6a8-59f8-11e8-8381-413a9666fe4b.png)

**Comment by pip3000** [comment]
Hi, I also have the same problem. It might have been the upgrade from February 2018 to April 2018 which created the problem because it had been working before with my Mashup.

**Comment by kfsjostrand** [comment]
Fixed in latest release v1.1.1
https://github.com/ClimberAB/ClimberContainer/releases/latest
